version: 2.1

jobs:
  test:
    parameters:
      docker-image:
        type: string
      clj-version:
        type: string
    working_directory: ~/project
    docker:
      - image: << parameters.docker-image >>
    environment:
      CLOJURE_VERSION: << parameters.clj-version >>
    steps:
      - checkout
      - restore_cache:
          key: project-{{ checksum "deps.edn" }}
      - run: clojure -X:test:$CLOJURE_VERSION
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: project-{{ checksum "deps.edn" }}

workflows:
  test_all_jdks:
    jobs:
      - test:
          matrix:
            parameters:
              docker-image:
                - clojure:temurin-8-noble
                - clojure:temurin-11-noble
                - clojure:temurin-17-noble
                - clojure:temurin-21-noble
                - clojure:temurin-22-noble
              clj-version: ["1.10", "1.11", "1.12"]
