version: 2.1

jobs:
  test:
    parameters:
      docker-image:
        type: string
      clj-version:
        type: string
        default: "1.11"
    working_directory: ~/project
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - restore_cache:
          key: project-{{ checksum "deps.edn" }}
      - run: clojure -X:attach:test :clj '"<< parameters.clj-version >>"'
      - save_cache:
          paths:
            - ~/.m2
          key: project-{{ checksum "deps.edn" }}

workflows:
  test_all_jdks:
    jobs:
      - test:
          matrix:
            parameters:
              docker-image:
                - clojure:temurin-8-jammy
                - clojure:temurin-11-jammy
                - clojure:temurin-17-jammy
                - clojure:temurin-21-jammy
                - clojure:temurin-22-jammy
              clj-version: ["1.10", "1.11", "1.12"]
